### ISSUE TITLE
including email field into user struct

### ISSUE THREAD

**Issue by elhussein-ali** [dghubble/go-twitter#1]
can you add email field into User struct

to activating the email fetch while calling VerifyCredentials with IncludeEmail = true

thanks

**Comment by dghubble** [comment]
Added the `Email` field, but note that email field will not be populated unless an application has been whitelisted by Twitter.

https://docs.fabric.io/android/twitter/request-user-email-address.html

**Comment by elhussein-ali** [comment]
thanks for your quick response :)
