### ISSUE TITLE
proxy issue 

### ISSUE THREAD

**Issue by herochinese** [dghubble/go-twitter#107]
Didn't display right information if need proxy to connect internet but without setup. Looks it works but not.

**Comment by dghubble** [comment]
Hey there. In an effort to reign in issues and use maintainer time in a healthy way to improve the library, I'm limiting issues to strictly bug reports that are clear and actionable.

Issues that are questions or support related will be (gently) closed. If the docs are insufficient to answer your question, consider asking your local Go guru or submitting an improvement.

Please re-open if yours was miscategorized.
