### ISSUE TITLE
How to get Hashtags from stream? 

### ISSUE THREAD

**Issue by k0fi** [dghubble/go-twitter#110]
Hello,
I'm wondering is there a way to get hashtags from stream in demux withouth need to parse demux.Tweet for hasthags?

**Comment by dghubble** [comment]
Hey there. In an effort to reign in issues and use maintainer time in a healthy way to improve the library, I'm limiting issues to strictly bug reports that are clear and actionable.

Issues that are questions or support related will be (gently) closed. If the docs are insufficient to answer your question, consider asking your local Go guru or submitting an improvement.

Please re-open if yours was miscategorized.
