### ISSUE TITLE
https://dev.twitter.com/rest/reference/post/friendships/create no rate limit in response

### ISSUE THREAD

**Issue by jscoys** [dghubble/go-twitter#111]
Hello,

I'm not finding any rate limit data in the response from https://dev.twitter.com/rest/reference/post/friendships/create resp (Using go-twitter API of course...).

Is it normal? Is this endpoint not returning information at all? I can see rate limit data for others like followers.list/ids...

Thx.

**Comment by dghubble** [comment]
Hey there. In an effort to reign in issues and use maintainer time in a healthy way to improve the library, I'm limiting issues to strictly bug reports that are clear and actionable.

Issues that are questions or support related will be (gently) closed. If the docs are insufficient to answer your question, consider asking your local Go guru or submitting an improvement.

Please re-open if yours was miscategorized.
