### ISSUE TITLE
How can I like a twitt? 

### ISSUE THREAD

**Issue by k0fi** [dghubble/go-twitter#112]
Hello,
I have made bot like this:

```
config := oauth1.NewConfig(consumerKey, consumerSecret)
	token := oauth1.NewToken(accessToken, accessSecret)

	// OAuth1 http.Client will automatically authorize Requests
	httpClient := config.Client(oauth1.NoContext, token)

	// Twitter client
	client := twitter.NewClient(httpClient)

	for t := range time.NewTicker(5 * time.Second).C {
		fmt.Println(t)

		// Search tweets to retweet
		searchParams := &twitter.SearchTweetParams{
			Query:      "#foo",
			Count:      100,
			ResultType: "recent",
			Lang:       "en",
		}

		searchResult, _, _ := client.Search.Tweets(searchParams)

		// Retweet
		for _, tweet := range searchResult.Statuses {
			tweet_id := tweet.ID
			client.Statuses.Retweet(tweet_id, &twitter.StatusRetweetParams{})
			client.Favorited(tweet_id, &twitter.StatusRetweetParams{})
		}
```

I'm wondering how can I `Like` the tweets while  retweeting them?

**Comment by FedericoPonzi** [comment]
You can check the API doc [here](https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/post-favorites-create)

Which says that:

> Note: favorites are now known as likes.

So you can do something like this:

```
favourite := twitter.FavoriteCreateParams{tweet.ID}
client.Favorites.Create(&favourite)
```

**Comment by dghubble** [comment]
Hey there. In an effort to reign in issues and use maintainer time in a healthy way to improve the library, I'm limiting issues to strictly bug reports that are clear and actionable.

Issues that are questions or support related will be (gently) closed. If the docs are insufficient to answer your question, consider asking your local Go guru or submitting an improvement.

Please re-open if yours was miscategorized.
