### ISSUE TITLE
json unmarshal error: DirectMessageEvents.apps is of type string

### ISSUE THREAD

**Issue by Xeoncross** [dghubble/go-twitter#115]
Encountering an error with the structure of the [Direct Message Events](https://github.com/dghubble/go-twitter/blob/master/twitter/direct_messages.go#L10) type. Documenting here while I work on a resolution.

`json: cannot unmarshal object into Go struct field DirectMessageEvents.apps of type string`

Only seems to impact certain accounts. Some accounts get an object for the `Apps` property. Since it's not important to me, I simply removed the field for now.

The [twitter api does not list an "apps" property](https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/api-reference/list-events).

**Comment by Xeoncross** [comment]
Only seems to effect certain accounts. Some accounts get an object for the `Apps` property. Since it's not important to me, I simply removed the field for now.

**Comment by stevenleeg** [comment]
I'm seeing this issue pop up as well. Did you end up finding a resolution apart from modifying the library?

**Comment by Xeoncross** [comment]
I thought I submitted a pull request but I guess not. @dghubble can you delete line 12 of [twitter/direct_messages.go](https://github.com/dghubble/go-twitter/blob/master/twitter/direct_messages.go#L12)?

The struct should be:

```
type DirectMessageEvents struct {
	Events         []DirectMessageEvent `json:"events"`
	NextCursor string                            `json:"next_cursor"`
}
```

**Comment by stevenleeg** [comment]
I've created a PR that addresses this issue, hopefully we can get @dghubble to merge it in so long as he approves.

**Comment by dghubble** [comment]
Solved by https://github.com/dghubble/go-twitter/commit/a34e9059cd58e96429cee9c8a87fd8d907da6843
