### ISSUE TITLE
How can we update StreamFilterParams for the existing Stream ?

### ISSUE THREAD

**Issue by KishoreKarunakaran** [dghubble/go-twitter#120]
Let's say I've created the stream with filters

```go
params := &twitter.StreamFilterParams{
    Track: []string{"kitten"},
    StallWarnings: twitter.Bool(true),
}
stream, err := client.Streams.Filter(params)
```

Later some point, I want to track few more keywords, How can we achieve it ? Is there a way to update the existing stream variable with new StreamFilterParams ?

**Comment by dghubble** [comment]
Hey there. In an effort to reign in issues and use maintainer time in a healthy way to improve the library, I'm limiting issues to strictly bug reports that are clear and actionable.

Issues that are questions or support related will be (gently) closed. If the docs are insufficient to answer your question, consider asking your local Go guru or submitting an improvement.

Please re-open if yours was miscategorized.
