### ISSUE TITLE
How to do integration testing

### ISSUE THREAD

**Issue by cbrgm** [dghubble/go-twitter#129]
Hi there,

I'd like to write tests for my application that uses go-twitter, without using a real twitter account.

Can anyone provide a good example how to do integration testing for go-twitter?
Is there a fake client available?

Cheers
Chris

**Comment by dghubble** [comment]
You can look at how go-twitter tests API request formats and response formats with a fake server implementation and perhaps use a similar strategy. If by integration tests, you mean you'd like to make real network calls to Twitter, go-twitter doesn't use that style of testing.
