### ISSUE TITLE
No LookUp for FriendsShips

### ISSUE THREAD

**Issue by EpicNem** [dghubble/go-twitter#134]
Hello, I need the request /friendships/lookup, which exist on Twitter API but not in go-twitter.
Which can return an array of connections for multiple users (array of user). I want to know connection "followed_by" for each friends without iterating and requesting with each friends id. 
Is there an equivalent of this? 
https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-friendships-lookup

May they are the /friendships/show solution but it need a source and target user id and it return single friendship response

Friendships/lookup will be implemented in the future?

**Comment by dghubble** [comment]
You're probably the main party looking to do `friendship/lookups`, mind sending a PR? I'm working toward removing this issue tracker.

**Comment by xVanilla** [comment]
Sorry for my english, it is not really good. Thanks for your answer! May I have not all understand

**Comment by dghubble** [comment]
Yes, please send a PR. The current issues are open since they have some historical context, but long term I'm planning to disable issues. PR's provide a good avenue for the public to contribute fixes (and the occassonal feature).
