### ISSUE TITLE
DirectMessages deprecated and broken

### ISSUE THREAD

**Issue by EpicNem** [dghubble/go-twitter#135]
Hi, 

All DirectMessages services are deprecated and not work since the new Twitter API from August 2018 (when they change the DirectMessage).

There are still any update. Twitter API Anaconda doesn't have updated this too.

Have you got any solution for that? Or maybe an update incoming?

**Comment by dghubble** [comment]
Please read https://github.com/dghubble/go-twitter/blob/master/CHANGES.md#112018
