### ISSUE TITLE
Low level stream parameters implementation

### ISSUE THREAD

**Issue by keremgocen** [dghubble/go-twitter#18]
I looked through repo to find implementation of parameters such as [delimited](https://dev.twitter.com/streaming/overview/request-parameters#delimited). Could you please guide me towards where to look for lower level parameters, how they are implemented if they are?

**Comment by dghubble** [comment]
There should be no reason to set `delimited=length` since we don't tokenize by counting bytes. A `bufio.Scanner` parses tokens from the stream as described https://github.com/dghubble/go-twitter/blob/master/twitter/streams.go#L235.

**Comment by dghubble** [comment]
Also, checkout https://dev.twitter.com/streaming/overview/processing under "Delimited Messages". The strategy is a client implementation detail. If you're finding a situation where it matters, file an issue to that effect please.
