### ISSUE TITLE
How to get my tweet's retweet info

### ISSUE THREAD

**Issue by sapnaSpaceo** [dghubble/go-twitter#21]
Hey Dalton,
http://www.jsoneditoronline.org/?id=bd7e2dcfdbe0affe043b84abfedcc65d 
This is my tweet struct I want information of users who retweeted my tweet. In this there is one retweet count I want detail of that user.
In Twitter Development console there is one api for this called "https://api.twitter.com/1.1/statuses/retweets/". Can you tell me how I can get same response by using your library?

**Comment by dghubble** [comment]
Previously, the statuses service only included the `/statuses/retweet/:id.json` POST endpoint, it did not include the `/statuses/retweets/:id.json` GET list endpoint. Its been added now, give this a shot to get a list of recent retweets of a Tweet.

```
retweetsParams := &twitter.StatusRetweetsParams{Count: 4}
retweets, resp, err := client.Statuses.Retweets(768156359191728128, retweetsParams)
fmt.Println(retweets, resp, err)
```
