### ISSUE TITLE
Add Friend List and ID Feature

### ISSUE THREAD

**Issue by jun0r** [dghubble/go-twitter#33]
Add a feature to retrieve the list of friends for a specific user.  According to Twitter, a user's friends are a list of users that the specified user follows.  The implementation would work the same as followers.go.  Referencing the following REST API documentation:
- https://dev.twitter.com/rest/reference/get/friends/ids
- https://dev.twitter.com/rest/reference/get/friends/list

**Comment by dghubble** [comment]
Closed by #34
