### ISSUE TITLE
Site Steaming

### ISSUE THREAD

**Issue by fayimora** [dghubble/go-twitter#38]
I am trying to write a script that streams tweets from multiple users. Unfortunately, I haven't had luck getting the streaming service running. When I run my code, it just exits. I was expecting it to run forever and print something to the console for every new message received.

```go
package main

import (
	"fmt"

	"github.com/dghubble/go-twitter/twitter"
	"github.com/dghubble/oauth1"
)

func main() {
	config := oauth1.NewConfig("_", "_")
	token := oauth1.NewToken("_", "_")
	httpClient := config.Client(oauth1.NoContext, token)

	// Twitter client
	client := twitter.NewClient(httpClient)

	// Verify Client
	// verifyParams := &twitter.AccountVerifyParams{
	// 	SkipStatus:   twitter.Bool(true),
	// 	IncludeEmail: twitter.Bool(true),
	// }
	// user, _, _ := client.Accounts.VerifyCredentials(verifyParams)
	
  siteParams := &twitter.StreamSiteParams{
		Follow: []string{"64431298"}, //  [fayimora]
	}

	stream, err := client.Streams.Site(siteParams)
	if err != nil {
		fmt.Println(err.Error())
	}

  // defer stream.Stop()
	// fmt.Println(stream.Messages)
	for msg := range stream.Messages {
		fmt.Println(msg)
	}
}

```

Am I missing something?

cc @dghubble

**Comment by fayimora** [comment]
I just realised that this might be because the site stream API is in closed beta.. 😢

**Comment by Xeoncross** [comment]
I'm using an authorized app and the the sitestreams seems to be working fine for me.

**Comment by dghubble** [comment]
Yeah, Firehose and Site streams require permission from Twitter. I can't help with that unfortunately.
