### ISSUE TITLE
include filter parameter in the searchtweetparam

### ISSUE THREAD

**Issue by cocodrino** [dghubble/go-twitter#41]
Hi, according to this documentation http://stackoverflow.com/questions/13920851/get-tweets-with-pictures-using-twitter-search-api you can set a filter parameter and filter tweets based in their multimedia content (image,video,etc)

I've not tested it yet and seems than it's not documented in the twitter api but without doubts it's a really useful parameter

thank you so much!!

**Comment by dghubble** [comment]
If you read the [Search API](https://dev.twitter.com/rest/public/search), notice filter is part of the Query (e.g. `puppy filter:media`).
