### ISSUE TITLE
Notify of backoff?

### ISSUE THREAD

**Issue by Xeoncross** [dghubble/go-twitter#49]
Handling [backoffs is transparent to the application](https://github.com/dghubble/go-twitter/blob/master/twitter/streams.go#L186). Is there some way to notify the client when a backoff is triggered? For debugging a simple fmt.Println() would work but a `chan bool` or `chan int (backofftime)` would be nice.

**Comment by Xeoncross** [comment]
On the client side:

	go func() {
		for d := range stream.Backoff {
			fmt.Println("sleep for", d)
		}
	}()

Then update `streams.go`

```
type Stream struct {
	...
	Backoff  chan time.Duration
}
```

and 

```
func newStream(client *http.Client, req *http.Request) *Stream {
	s := &Stream{
		...
		Backoff:  make(chan time.Duration),
	}
	...
}

```

and

```
func (s *Stream) retry(req *http.Request, expBackOff backoff.BackOff, aggExpBackOff backoff.BackOff) {
...
		if wait == backoff.Stop {
			return
		}

		if wait.Seconds() > 0 {
			s.Backoff <- wait
		}

		sleepOrDone(wait, s.done)
...
}
```

**Comment by dghubble** [comment]
I agree, a Backoff channel on the Stream type could be quite nice. Feel free to send a PR if you're motivated.

**Comment by dghubble** [comment]
Closing for now since its been a long time. We may revisit if there is a need for backoff notifications since this is a clean way it could be done.
