### ISSUE TITLE
only 115 characters are provided on tweets

### ISSUE THREAD

**Issue by jwmurray** [dghubble/go-twitter#56]
When I run the user-auth.go example, only the first 115 characters of the tweet are shown.  Any idea why this would be the case?  The full tweet is truncated with an elipsis ...

> user-auth.go
....
@{<nil> Fri Mar 31 14:11:01 +0000 2017 <nil> 0xc420072900 1 false  847813487522873346 847813487522873346  0  0  en false 0 false <nil> <a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a> map[] **Daggett County Sheriff issues reminder to  public to use caution on and around the Green River due to increased flo…** https://t.co/7jyQiLD036 <nil> true 0xc4204e5200 false []  <nil> 0  <nil>}

**Comment by steve-winter** [comment]
It appears `tweet_mode=extended` is required to get the full version, but I do not believe that is supported by this library yet. I am looking at implementing it now, will share update when I have more information.

**Comment by steve-winter** [comment]
@dghubble - Please let me know if you are accepting pull requests for this, I have enabled full_text for search and happy to push.

**Comment by dghubble** [comment]
Sure, please send a PR and it may be included.

**Comment by ljfio** [comment]
Looks like "classic tweets" will include an additional field in JSON for users in a "compatibility mode" unless the "extended mode" is specified.

In [my repo](/ljfio/go-twitter/tree/extended) I added the basic two elements for extracting the full 140 character text.

I'd be grateful to know if this is an option you'd consider and if I should change it in anyway to match your code better?

**Comment by dghubble** [comment]
Sure, include the ExtendedTweet. New fields included in Twitter API JSON responses, but not deserialized by this package aren't non-controversial. The aim is to match them so feel free.
