### ISSUE TITLE
Access raw json for Streaming API

### ISSUE THREAD

**Issue by timogoosen** [dghubble/go-twitter#58]
Is there some way to access the raw json from the streaming API without changing the codebase or writing my own code? I'd like to try sending the streaming data into something like Kafka,but from what I've read the data needs to be in json.

**Comment by dghubble** [comment]
No, the [Stream](https://github.com/dghubble/go-twitter/blob/master/twitter/streams.go#L147) provides a Messages `channel interface{}` and JSON [decodes](https://github.com/dghubble/go-twitter/blob/master/twitter/streams.go#L262) tokens. You will need to make modifications to suit your needs.
