### ISSUE TITLE
Are errors passed to the "All" demux callback?

### ISSUE THREAD

**Issue by Xeoncross** [dghubble/go-twitter#67]
It looks like HTTP errors from streaming apis are passed to the [`Messages` queue](https://github.com/dghubble/go-twitter/blob/master/twitter/streams.go#L196). Does that mean any errors will be available in the `demux.All = func(message interface{}) ...` callback?

**Comment by dghubble** [comment]
Yes, `demux.All` just doesn' filter out any of the messages. The Demux is mainly useful for doing type switching for you and calling your different functions for different types of messages - if you only set a `demux.All = func(message interface{})`, there isn't too much reason to be using the demux.
