### ISSUE TITLE
How to get expanded_url

### ISSUE THREAD

**Issue by crosscue** [dghubble/go-twitter#81]
Hello,

I'm using the filter stream and trying to get the expanded_url from within the entities URLs object. The following code allows me to get the twitter.URLEntity, however I don't seem to be able to get the ExpandedURL from within it:

`demux.Tweet = func(tweet *twitter.Tweet) {`
`fmt.Println(tweet.Entities.Urls)`
`}`

I tried this:

`d := tweet.Entities.Urls`
`log.Println(d.ExpandedURL)`

...but that didn't work.

**Comment by dghubble** [comment]
Entities.Urls is a slice.

https://github.com/dghubble/go-twitter/blob/master/twitter/entities.go#L9

**Comment by cskonopka** [comment]
Do you have a full example of this outside of just a link to the go file?
