### ISSUE TITLE
Update documentation to show how to generate an access token?

### ISSUE THREAD

**Issue by ns-cweber** [dghubble/go-twitter#82]
I'm trying to run the app-auth example with the access token retrieved from the "Your Access Token" section of my application on apps.twitter.com, but it's always returning "Invalid or expired token." I assume I'm doing this wrong, but I can't find documentation on how to do it correctly. While it's obviously Twitter's responsibility to provide sane documentation, it would be helpful to users of this library if this library's documentation pointed them in the right direction or included information about how to get the access token in the app-auth example.

**Comment by dghubble** [comment]
Try https://github.com/dghubble/go-twitter/pull/31

**Comment by ns-cweber** [comment]
Hmm, I did exactly that, and I tried rolling the token a couple of times for good measure.

**Comment by ns-cweber** [comment]
Yep, that fixes it. So is the issue that Twitter's documentation was incorrect and that the access token simply doesn't work, or that this library doesn't correctly implement the flow that would allow it to work?
