### ISSUE TITLE
Unable to fetch User timelines using App Authentication

### ISSUE THREAD

**Issue by icyflame** [dghubble/go-twitter#88]
I tried this in an application. When that didn't work, I tried it with the default `app-auth.go` example script (with error reporting) [Script](https://gist.github.com/icyflame/7cbc4e70647619f01277542c248b319c)

This is the output from this script:

```sh
$ ACCESS_CODE="....." go run app-auth.go
USERS SHOW:
&{ContributorsEnabled:false CreatedAt: DefaultProfile:false DefaultProfileImage:false Description: Email: Entities:<nil> FavouritesCount:0 FollowRequestSent:false Following:false FollowersCount:0 FriendsCount:0 GeoEnabled:false ID:0 IDStr: IsTranslator:false Lang: ListedCount:0 Location: Name: Notifications:false ProfileBackgroundColor: ProfileBackgroundImageURL: ProfileBackgroundImageURLHttps: ProfileBackgroundTile:false ProfileBannerURL: ProfileImageURL: ProfileImageURLHttps: ProfileLinkColor: ProfileSidebarBorderColor: ProfileSidebarFillColor: ProfileTextColor: ProfileUseBackgroundImage:false Protected:false ScreenName: ShowAllInlineMedia:false Status:<nil> StatusesCount:0 Timezone: URL: UtcOffset:0 Verified:false WithheldInCountries:[] WithholdScope:}
Error with Users show: twitter: 89 Invalid or expired token.
USERS LOOKUP:
[]
Error with users lookup: twitter: 89 Invalid or expired token.
STATUSES SHOW:
&{Coordinates:<nil> CreatedAt: CurrentUserRetweet:<nil> Entities:<nil> FavoriteCount:0 Favorited:false FilterLevel: ID:0 IDStr: InReplyToScreenName: InReplyToStatusID:0 InReplyToStatusIDStr: InReplyToUserID:0 InReplyToUserIDStr: Lang: PossiblySensitive:false RetweetCount:0 Retweeted:false RetweetedStatus:<nil> Source: Scopes:map[] Text: FullText: DisplayTextRange:[0 0] Place:<nil> Truncated:false User:<nil> WithheldCopyright:false WithheldInCountries:[] WithheldScope: ExtendedEntities:<nil> ExtendedTweet:<nil> QuotedStatusID:0 QuotedStatusIDStr: QuotedStatus:<nil>}
Error with status show: twitter: 89 Invalid or expired token.
STATUSES LOOKUP:
[]
Error with status lookup twitter: 89 Invalid or expired token.
OEMBED TWEET:
&{URL:https://twitter.com/dghubble/status/691076766878691329 ProviderURL:https://twitter.com ProviderName:Twitter AuthorName:Dalton Hubble Version:1.0 AuthorURL:https://twitter.com/dghubble Type:rich HTML:<blockquote class="twitter-tweet" data-width="500"><p lang="en" dir="ltr">Healthy SF Tax? Delightful...</p>&mdash; Dalton Hubble (@dghubble) <a href="https://twitter.com/dghubble/status/691076766878691329?ref_src=twsrc%5Etfw">January 24, 2016</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
 Height:0 Width:500 CacheAge:3153600000}
Error with Oembed tweet: <nil>
USER TIMELINE:
[]
Error with User timeline: twitter: 89 Invalid or expired token.
SEARCH TWEETS:
&{Statuses:[] Metadata:<nil>}
SEARCH METADATA:
<nil>
Error with Search: twitter: 89 Invalid or expired token.
```

The access code is from a brand new application that I created on apps.twitter.com. The permissions are read-and-write. The same thing works if I use the OAuth 1.0 flow, as in the Consumer Key, Consumer Secret, this Access Code and an Access Secret.

![screenshot from 2017-12-15 08-51-03 fixed](https://user-images.githubusercontent.com/3668034/34025435-ea56f632-e175-11e7-9310-25957e06c84d.png)
***
![screenshot from 2017-12-15 08-51-13 fixed](https://user-images.githubusercontent.com/3668034/34025436-ea93c0ee-e175-11e7-97f1-779b32ab4341.png)

I used the access code from the second image.

**Comment by icyflame** [comment]
Ah, so I tried it again after doing the OAuth2 authentication. As in, I ran:

```sh
curl -v -X POST \
       -d 'grant_type=client_credentials' \
       --header "Authorization: Basic  <STR>" \
       --header "Content-Type: application/x-www-form-urlencoded;charset=UTF-8" \
       https://api.twitter.com/oauth2/token
```

where `<STR>`=`Base64("Consumer_KEY:Consumer_SECRET")` (as given in Step 1 of https://developer.twitter.com/en/docs/basics/authentication/overview/application-only)

If this is the intended usage of this library, can I make a patch adding the same to the readme? Because the current terminology is very confusing.

**Comment by icyflame** [comment]
The go script for getting oauth2 access token: https://gist.github.com/icyflame/08d0d114fbc08b7948164f3214b83f82

**Comment by ahmetb** [comment]
+1 This is super confusing and there's no references to what the access token value for OAuth2  should be in this repo! This is making the getting started experience way more difficult.

The example at https://github.com/dghubble/go-twitter/blob/c4115fa44a928413e0b857e0eb47376ffde3a61a/examples/app-auth.go gives the impression that "oh just get your access token value from your https://apps.twitter.com/ and pass it to this program.

**Comment by ahmetb** [comment]
@icyflame I cleaned up your code quite a bit (there were some unidiomatic Go usages) and turned into this helper function. If anyone runs into the same problem, feel free to use this:

```go
package main

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
)

func getBearerToken(consumerKey, consumerSecret string) (string, error) {
	req, err := http.NewRequest("POST", "https://api.twitter.com/oauth2/token",
		strings.NewReader("grant_type=client_credentials"))

	if err != nil {
		return "", fmt.Errorf("cannot create /token request: %+v", err)
	}

	b64Token := base64.StdEncoding.EncodeToString(
		[]byte(fmt.Sprintf("%s:%s", consumerKey, consumerSecret)))
	req.Header.Add("Authorization", "Basic "+b64Token)
	req.Header.Add("Content-Type", "application/x-www-form-urlencoded;charset=UTF-8")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("/token request failed: %+v", err)
	}
	defer resp.Body.Close()

	var v struct {
		AccessToken string `json:"access_token"`
	}

	if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
		return "", fmt.Errorf("error parsing json in /token response: %+v", err)
	}
	if v.AccessToken == "" {
		return "", fmt.Errorf("/token response does not have access_token")
	}
	return v.AccessToken, nil
}
```

**Comment by icyflame** [comment]
> oh just get your access token value from your https://apps.twitter.com/ and pass it to this program

@ahmetb EXACTLY! Thanks for posting this. I am going to open a patch to the documentation that mentions this clearly.

_P.S._ I am sorry about the goofs, I am rather new to Go and I have been just writing stuff to make it work. Thanks for cleaning it up!

**Comment by ahmetb** [comment]
@icyflame FWIW I think this method doesn't always work. See #92 for a case that doesn't work with the OAuth2 bearer token. It would be diagnose what’s up first.

**Comment by bobg** [comment]
Even more idiomatic is to use the `oauth2/clientcredentials` package, which encapsulates this flow. You don't even need to get the access token explicitly.

```
import (
	"github.com/dghubble/go-twitter/twitter"
	"golang.org/x/oauth2"
	"golang.org/x/oauth2/clientcredentials"
)

...

config := &clientcredentials.Config{
	ClientID:     consumerKey,
	ClientSecret: consumerSecret,
	TokenURL:     "https://api.twitter.com/oauth2/token",
}
httpClient := config.Client(oauth2.NoContext)
twClient := twitter.NewClient(httpClient)
```
