### ISSUE TITLE
Stream new followers for authenticated account

### ISSUE THREAD

**Issue by gianarb** [dghubble/go-twitter#90]
Hello! I would like to thank you for your hard work. The API is friendly and I used it in a couple of minutes without any trouble.

I am trying to stream new followers but I am not able to find any good way. Is it possible?

Thanks a lot

**Comment by dghubble** [comment]
Hey there. In an effort to reign in issues and use maintainer time in a healthy way to improve the library, I'm limiting issues to strictly bug reports that are clear and actionable.

Issues that are questions or support related will be (gently) closed. If the docs are insufficient to answer your question, consider asking your local Go guru or submitting an improvement.

Please re-open if yours was miscategorized.
