### ISSUE TITLE
Add error handling to examples

### ISSUE THREAD

**Issue by ahmetb** [dghubble/go-twitter#91]
There's no err handling in files like https://github.com/dghubble/go-twitter/blob/c4115fa44a928413e0b857e0eb47376ffde3a61a/examples/app-auth.go

This is not great for beginners like myself because they'll end up doing something wrong very easily such as passing the wrong token etc and they'll look at printed zero-values of structs which makes no sense.

**Comment by dghubble** [comment]
Its an example main.go. Its meant to be as short and as illustrative of available API calls as possible. How you choose to handle errors very much depends on your use case.
