### ISSUE TITLE
no example of StallWarnings

### ISSUE THREAD

**Issue by ahmetb** [dghubble/go-twitter#93]
After reading the godoc and examples, it's not clear to me how stalls is received in the following code.

I just keep getting more and more tweets with no stall warnings. Is "stall warning" a tweet?

There's no errCh as far as I can tell, returned from the stream function. How are we supposed to get these warnings?

```

	params := &twitter.StreamFilterParams{
		StallWarnings: twitter.Bool(true),
		Track: []string{
			"and",
		},
	}
	stream, err := client.Streams.Filter(params)
	if err != nil {
		log.Fatalf("streaming tweets failed: %+v", err)
	}
	demux := twitter.NewSwitchDemux()
	demux.Tweet = func(tweet *twitter.Tweet) {
		fmt.Println(tweet.Text)
	}
	go demux.HandleChan(stream.Messages)
```

**Comment by dghubble** [comment]
Hey there. In an effort to reign in issues and use maintainer time in a healthy way to improve the library, I'm limiting issues to strictly bug reports that are clear and actionable.

Issues that are questions or support related will be (gently) closed. If the docs are insufficient to answer your question, consider asking your local Go guru or submitting an improvement.

Please re-open if yours was miscategorized.
