### ISSUE TITLE
Geocode parameter is not giving the right results for app-auth

### ISSUE THREAD

**Issue by carthics** [dghubble/go-twitter#97]
The search API has a parameter called Geocode. This parameter searches tweets within a specified radius. For example:

https://api.twitter.com/1.1/search/tweets.json?q="Trump"&geocode="20.59,78.96,100km" gives tweets within a 100 km of the specified coordinates. This is done by checking geotagged tweets and then Twitter also checks the user profile information (as fallback). The problem is when I pass the geocode parameter through the go-twitter library the system checks for geotagged tweets but does not check the user profile as fallback. I am not sure if anyone else has encountered the same issue.

**Comment by dghubble** [comment]
Hey there. In an effort to reign in issues and use maintainer time in a healthy way to improve the library, I'm limiting issues to strictly bug reports that are clear and actionable.

Issues that are questions or support related will be (gently) closed. If the docs are insufficient to answer your question, consider asking your local Go guru or submitting an improvement.

Please re-open if yours was miscategorized.
