### ISSUE TITLE
problem with search

### ISSUE THREAD

**Issue by jnovotny** [dghubble/go-twitter#98]
My apologies, I'm a Go newbie and trying to simply get results in JSON format.
I have this code:

```
_, resp, err := client.Search.Tweets(&twitter.SearchTweetParams{
		Query: "food"
	})
	fmt.Println(resp)
```
and it prints out
```
 &{200 OK 200 HTTP/2.0 2 0 map[Set-Cookie:[personalization_id="v1_7au7R3yJcbb39ND46d4Kew=="; Expires=Wed, 01 Apr 2020 14:11:42 UTC; Path=/; Domain=.twitter.com lang=en; Path=/ guest_id=v1%3A152267830262179011; Expires=Wed, 01 Apr 2020 14:11:42 UTC; Path=/; Domain=.twitter.com] Strict-Transport-Security:[max-age=631138519] Cache-Control:[no-cache, no-store, must-revalidate, pre-check=0, post-check=0] Content-Type:[application/json;charset=utf-8] Server:[tsa_k] X-Rate-Limit-Limit:[180] X-Rate-Limit-Reset:[1522678957] X-Transaction:[003a137c003017c2] Content-Disposition:[attachment; filename=json.json] Status:[200 OK] X-Access-Level:[read-write] Pragma:[no-cache] X-Frame-Options:[SAMEORIGIN] X-Rate-Limit-Remaining:[174] X-Content-Type-Options:[nosniff] X-Response-Time:[302] X-Twitter-Response-Tags:[BouncerCompliant] X-Xss-Protection:[1; mode=block; report=https://twitter.com/i/xss_report] Date:[Mon, 02 Apr 2018 14:11:42 GMT] Expires:[Tue, 31 Mar 1981 05:00:00 GMT] Last-Modified:[Mon, 02 Apr 2018 14:11:42 GMT] X-Connection-Hash:[5ca21737cfea29c628799edc00db0458]] 0xc42036a1b0 -1 [] false true map[] 0xc4201c6200 0xc4204c6bb0}
```

My first question is why I don't see results and the second is how can I print out JSON response?

Thanks a lot, Jason

**Comment by cskonopka** [comment]
It worked once for me and I now experiencing the same type of thing but my expiration is rather absurd, 1981

`
&{200 OK 200 HTTP/2.0 2 0 map[X-Xss-Protection:[1; mode=block; report=https://twitter.com/i/xss_report] Server:[tsa_b] X-Frame-Options:[SAMEORIGIN] X-Response-Time:[118] Set-Cookie:[personalization_id="v1_HX+oVUKj216NccOHJ2ynIg=="; Expires=Tue, 02 Jun 2020 02:52:07 GMT; Path=/; Domain=.twitter.com lang=en; Path=/ guest_id=v1%3A152799432761203022; Expires=Tue, 02 Jun 2020 02:52:07 GMT; Path=/; Domain=.twitter.com] X-Access-Level:[read-write] X-Connection-Hash:[da8e9518c070cfb8a5998bff9bef45ba] X-Content-Type-Options:[nosniff] Cache-Control:[no-cache, no-store, must-revalidate, pre-check=0, post-check=0] Content-Type:[application/json;charset=utf-8] Expires:[Tue, 31 Mar 1981 05:00:00 GMT] Pragma:[no-cache] X-Transaction:[009fc89500ad8e97] X-Twitter-Response-Tags:[BouncerCompliant] Status:[200 OK] Strict-Transport-Security:[max-age=631138519] X-Rate-Limit-Limit:[180] X-Rate-Limit-Remaining:[178] Content-Disposition:[attachment; filename=json.json] Date:[Sun, 03 Jun 2018 02:52:07 GMT] Last-Modified:[Sun, 03 Jun 2018 02:52:07 GMT] X-Rate-Limit-Reset:[1527994497]] 0xc42010e7e0 -1 [] false true map[] 0xc4200fa100 0xc4203340b0}
`

**Comment by dghubble** [comment]
Hey there. In an effort to reign in issues and use maintainer time in a healthy way to improve the library, I'm limiting issues to strictly bug reports that are clear and actionable.

Issues that are questions or support related will be (gently) closed. If the docs are insufficient to answer your question, consider asking your local Go guru or submitting an improvement.

Please re-open if yours was miscategorized.
